services:
  db:
    image: postgis/postgis:15-3.3-alpine
    container_name: ze-delivery-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ze_delivery_db
    ports:
      - "5433:5432"
    volumes:
      - ze_postgres_data:/var/lib/postgresql/data

volumes:
  ze_postgres_data: